{% set name = "castepinput" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/castepinput-{{ version }}.tar.gz
  sha256: 8cdb6f6f473db24e4eab794c5dff68f7b3594cb6ad2526f0050978f93dcd9904

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - python >=3.6
    - six

test:
  imports:
    - castepinput
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zhubonan/castepinput
  summary: A general reader/writer for CASTEP inputs
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisjsewell
