{% set name = "castepinput" %}
{% set version = "0.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/castepinput-{{ version }}.tar.gz
  sha256: 03c4966e58783c95b4990f74ff7dd29bcc669156c5abea27e9e9c43a2ce430e7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy
    - python >=3.6
    - six

test:
  imports:
    - castepinput
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/zhubonan/castepinput
  summary: A general reader/writer for CASTEP inputs
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisjsewell
